-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type override. The third value is an optional increment multiplier for consumables. (feel free to expand the table with any other values you might need (i.e. special initial values, etc.)!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
WEAPON_ITEM_ID = 50000000
GADGET_ITEM_ID = 50000040
PLANET_ITEM_ID = 50000050
ITEM_MAPPING = {
	[WEAPON_ITEM_ID + 00000] = { { "ShockBlaster" } },
	[WEAPON_ITEM_ID + 00001] = { { "NitroLauncher" } },
	[WEAPON_ITEM_ID + 00002] = { { "N60Storm" } },
	[WEAPON_ITEM_ID + 00003] = { { "PlasmaWhip" } },
	[WEAPON_ITEM_ID + 00004] = { { "Infector" } },
	[WEAPON_ITEM_ID + 00005] = { { "SuckCannon" } },
	[WEAPON_ITEM_ID + 00006] = { { "SpittingHydra" } },
	[WEAPON_ITEM_ID + 00007] = { { "AgentsOfDoom" } },
	[WEAPON_ITEM_ID + 00008] = { { "FluxRifle" } },
	[WEAPON_ITEM_ID + 00009] = { { "Annihilator" } },
	[WEAPON_ITEM_ID + 00010] = { { "HoloShieldGlove" } },
	[WEAPON_ITEM_ID + 00011] = { { "DiskBladeGun" } },
	[WEAPON_ITEM_ID + 00012] = { { "RiftInducer" } },
	[WEAPON_ITEM_ID + 00013] = { { "QwackORay" } },
	[WEAPON_ITEM_ID + 00014] = { { "RY3N0" } },
	[WEAPON_ITEM_ID + 00015] = { { "MiniTurretGlove" } },
	[WEAPON_ITEM_ID + 00016] = { { "LavaGun" } },
	[WEAPON_ITEM_ID + 00017] = { { "ShieldCharger" } },
	[WEAPON_ITEM_ID + 00018] = { { "Bouncer" } },
	[WEAPON_ITEM_ID + 00019] = { { "PlasmaCoil" } },
	-- Progressive Weapons --
	[WEAPON_ITEM_ID + 00020] = { { "ShockBlaster" } },
	[WEAPON_ITEM_ID + 00021] = { { "NitroLauncher" } },
	[WEAPON_ITEM_ID + 00022] = { { "N60Storm" } },
	[WEAPON_ITEM_ID + 00023] = { { "PlasmaWhip" } },
	[WEAPON_ITEM_ID + 00024] = { { "Infector" } },
	[WEAPON_ITEM_ID + 00025] = { { "SuckCannon" } },
	[WEAPON_ITEM_ID + 00026] = { { "SpittingHydra" } },
	[WEAPON_ITEM_ID + 00027] = { { "AgentsOfDoom" } },
	[WEAPON_ITEM_ID + 00028] = { { "FluxRifle" } },
	[WEAPON_ITEM_ID + 00029] = { { "Annihilator" } },
	[WEAPON_ITEM_ID + 00030] = { { "HoloShieldGlove" } },
	[WEAPON_ITEM_ID + 00031] = { { "DiskBladeGun" } },
	[WEAPON_ITEM_ID + 00032] = { { "RiftInducer" } },
	[WEAPON_ITEM_ID + 00033] = { { "QwackORay" } },
	[WEAPON_ITEM_ID + 00034] = { { "RY3N0" } },
	[WEAPON_ITEM_ID + 00035] = { { "MiniTurretGlove" } },
	[WEAPON_ITEM_ID + 00036] = { { "LavaGun" } },
	[WEAPON_ITEM_ID + 00037] = { { "ShieldCharger" } },
	[WEAPON_ITEM_ID + 00038] = { { "Bouncer" } },
	[WEAPON_ITEM_ID + 00039] = { { "PlasmaCoil" } },
	-- Gadget / Item / VidComic --
	[GADGET_ITEM_ID + 00000] = { { "hacker" } },
	[GADGET_ITEM_ID + 00001] = { { "hyperShot" } },
	[GADGET_ITEM_ID + 00002] = { { "refractor" } },
	[GADGET_ITEM_ID + 00003] = { { "tyhrraGuise" } },
	[GADGET_ITEM_ID + 00004] = { { "gravBoots" } },
	[GADGET_ITEM_ID + 00005] = { { "BoltGrabberV2" } },
	[GADGET_ITEM_ID + 00006] = { { "MapOMatic" } },
	[GADGET_ITEM_ID + 00007] = { { "NanoPak" } },
	[GADGET_ITEM_ID + 00008] = { { "WarpPad" } },
	[GADGET_ITEM_ID + 00009] = { { "pda" } },
	[GADGET_ITEM_ID + 00010] = { { "chargeBoots" } },
	[GADGET_ITEM_ID + 00011] = { { "BoxBreaker" } },
	[GADGET_ITEM_ID + 00035] = { { "vidComic" } },
	[GADGET_ITEM_ID + 00040] = { { "Armor" } },
	-- Planet --
	[PLANET_ITEM_ID + 00005] = { { "Marcadia" } },
	[PLANET_ITEM_ID + 00006] = { { "Annihilation" } },
	[PLANET_ITEM_ID + 00007] = { { "Aquatos" } },
	[PLANET_ITEM_ID + 00008] = { { "Tyhrranosis" } },
	[PLANET_ITEM_ID + 00009] = { { "Daxx" } },
	[PLANET_ITEM_ID + 00010] = { { "ObaniGemini" } },
	[PLANET_ITEM_ID + 00011] = { { "Blackwater" } },
	[PLANET_ITEM_ID + 00012] = { { "Holostar" } },
	[PLANET_ITEM_ID + 00013] = { { "ObaniDraco" } },
	[PLANET_ITEM_ID + 00014] = { { "ZeldrinStarport" } },
	[PLANET_ITEM_ID + 00015] = { { "Metropolis" } },
	[PLANET_ITEM_ID + 00016] = { { "CrashSite" } },
	[PLANET_ITEM_ID + 00017] = { { "Aridia" } },
	[PLANET_ITEM_ID + 00018] = { { "QwarksHideout" } },
	[PLANET_ITEM_ID + 00019] = { { "Koros" } },
	[PLANET_ITEM_ID + 00020] = { { "CommandCenter" } },

	-- -- handle progressive_toggle as toggle, only changing it's active state
	-- [BASE_ITEM_ID + 00003] = { { "progressive_toggle", "toggle" } },
	-- -- multiple items on this id, add the consumable 3 times
	-- [BASE_ITEM_ID + 00004] = { { "toggle" }, { "consumable", nil, 3 } }
}
